version: '3'

services:
  mongo:
    image: mongo:4.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ~/.docker-data/mongodb/data/db
    ports:
      - 27017:27017
  