version: '3'

services:
  mongo:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ~/.docker-data/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  